
services:
  localstack:
    container_name: localstack_fleexa
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - SERVICES=dynamodb,lambda
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"